### ISSUE TITLE
Can't delete a Fondfolio that has contributions

### ISSUE THREAD

**Issue by feeohnah** [studio-cartogram/fondfolio#125]

**Comment by cartogram** [comment]
The issue with this is that we don't have an on delete behavior set in our relation between fondfolios and contributions. 

In order to support deletion, we would need to migrate out database to have a CASCADE on delete behavior on those 2 tables. A guide for doing this on a new database is here: 
https://www.prisma.io/docs/guides/database-workflows/cascading-deletes/postgresql

I do not know how or want to deal with migrating our database at this time. I think we hold off until the prisma migrate stuff works for these sort of operations.

**Comment by cartogram** [comment]
There would be some incantation of this command on each of the DBs. Probably in a script.

https://www.postgresql.org/docs/9.4/sql-altertable.html
